#!/usr/bin/env python

import os
import appdirs
import pkg_resources
import configobj
import shutil
import oneview_redfish_toolkit.app

ENCODING='utf-8'
CFG_DIR_NAME = 'oneview-redfish-toolkit'
REDFISH_CFG_FILE_NAME = 'redfish.conf'
LOGGING_CFG_FILE_NAME = 'logging.conf'

REGISTRY_DIR_NAME = 'registry'
SCHEMAS_DIR_NAME = 'schemas'

CERTS_DIR_NAME = 'certs'
CERTS_CRT_FILE_NAME = 'self-signed.crt'
CERTS_KEY_FILE_NAME = 'self-signed.key'


def get_config_file_path(file_name):
    """Read redfish configuration file and return its contents
    """
    cfg_dir = appdirs.user_config_dir(CFG_DIR_NAME)
    cgf_file_path = os.path.join(cfg_dir, file_name)

    if not os.path.isfile(cgf_file_path):
        create_config_file(cfg_dir, file_name)

    return cgf_file_path


def get_config_file(file_name):
    """Read configuration file and return its contents
    """
    cgf_file_path = get_config_file_path(file_name)
    config = configobj.ConfigObj(cgf_file_path, raise_errors=True, encoding=ENCODING, default_encoding=ENCODING)
    return config


def create_config_file(file_dir, file_name):
    """Create config file
    """
    source = pkg_resources.resource_filename(oneview_redfish_toolkit.__name__, os.path.join('conf', file_name))
    os.makedirs(name=file_dir, exist_ok=True)
    shutil.copyfile(source, os.path.join(file_dir, file_name))


def set_redfish_config(file_path, user_settings={}):
    conf = configobj.ConfigObj(file_path, raise_errors=True, encoding=ENCODING, default_encoding=ENCODING)
    conf.merge(user_settings)
    conf.write()


def get_config_dir_path(dir_name):
    """Returns path from the directory name passed as arguments
    on the user config directory. If the directory not exists
    will be created copying files from application lib dir.
    """
    cfg_dir = appdirs.user_config_dir(CFG_DIR_NAME)
    cgf_dir_path = os.path.join(cfg_dir, dir_name)

    if not os.path.isdir(cgf_dir_path):
        create_config_dir(cfg_dir, dir_name)

    return cgf_dir_path


def create_config_dir(path_dir, dir_name):
    """Create config directory copying from application lib
    """
    source = pkg_resources.resource_filename(oneview_redfish_toolkit.__name__, dir_name)
    os.makedirs(name=path_dir, exist_ok=True)
    shutil.copytree(source, os.path.join(path_dir, dir_name))


if __name__ == '__main__':
    config_logging_path = get_config_file_path(LOGGING_CFG_FILE_NAME)

    config_path = get_config_file_path(REDFISH_CFG_FILE_NAME)
    config = get_config_file(REDFISH_CFG_FILE_NAME)
    
    ov_ip = config['oneview_config']['ip']
    schema_dir = config['redfish']['schema_dir']
    registry_dir = config['redfish']['registry_dir']
    certs_dir = config['ssl']['SSLCertFile']

    settings = {}
    settings['oneview_config'] = {}
    settings['redfish'] = {}
    settings['ssl'] = {}

    if not ov_ip:
        ov_ip = str(input('Set Oneview IP: '))
        settings['oneview_config']['ip'] =  ov_ip

    if not schema_dir:
        schemas_dir = get_config_dir_path(SCHEMAS_DIR_NAME)
        settings['redfish']['schema_dir'] =  schemas_dir

    if not registry_dir:
        registry_dir = get_config_dir_path(REGISTRY_DIR_NAME)
        settings['redfish']['registry_dir'] =  registry_dir

    if not certs_dir:
        certs_dir = get_config_dir_path(CERTS_DIR_NAME)
        settings['ssl']['SSLCertFile'] =  os.path.join(certs_dir, CERTS_CRT_FILE_NAME)
        settings['ssl']['SSLKeyFile'] =  os.path.join(certs_dir, CERTS_KEY_FILE_NAME)

    print('Configuration file saved: "' + config_path + '"')

    set_redfish_config(config_path, settings)

    oneview_redfish_toolkit.app.main(config_path, config_logging_path)